spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
  mongodb:
    embedded:
      version: 4.0.21

#  data:
#    cassandra:
#      keyspace-name: taco_cloud
#      schema-action: recreate
#      local-datacenter: datacenter1
